/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetofinal;

import javax.swing.JOptionPane;
/**
 *
 * @author mathe
 */
public class menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menu.class.getName());
    
    Funcionario f = new Funcionario();
    Dependentes dependentes = new Dependentes();
    
    public menu() {
        initComponents();
        setLocationRelativeTo(null);
        jScrollPane1.setVisible(false);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaListagem = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastrar = new javax.swing.JMenu();
        cadastrarFuncionario = new javax.swing.JMenuItem();
        cadastrarDependente = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenu();
        editarFuncionario = new javax.swing.JMenuItem();
        editarDependente = new javax.swing.JMenuItem();
        menuListar = new javax.swing.JMenu();
        listarFuncionarios = new javax.swing.JMenuItem();
        listarDependentes = new javax.swing.JMenuItem();
        menuDeletar = new javax.swing.JMenu();
        deletarFuncionario = new javax.swing.JMenuItem();
        deletarDependente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2026-06-17 at 19.08.48.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");

        txtAreaListagem.setEditable(false);
        txtAreaListagem.setColumns(20);
        txtAreaListagem.setRows(5);
        txtAreaListagem.setBorder(null);
        jScrollPane1.setViewportView(txtAreaListagem);

        menuCadastrar.setText("Cadastrar");

        cadastrarFuncionario.setText("Cadastrar Funcionário");
        cadastrarFuncionario.addActionListener(this::cadastrarFuncionarioActionPerformed);
        menuCadastrar.add(cadastrarFuncionario);

        cadastrarDependente.setText("Cadastrar Dependente");
        cadastrarDependente.addActionListener(this::cadastrarDependenteActionPerformed);
        menuCadastrar.add(cadastrarDependente);

        jMenuBar1.add(menuCadastrar);

        menuEditar.setText("Editar");

        editarFuncionario.setText("Editar Funcionário");
        editarFuncionario.addActionListener(this::editarFuncionarioActionPerformed);
        menuEditar.add(editarFuncionario);

        editarDependente.setText("Editar Dependente");
        editarDependente.addActionListener(this::editarDependenteActionPerformed);
        menuEditar.add(editarDependente);

        jMenuBar1.add(menuEditar);

        menuListar.setText("Listar");

        listarFuncionarios.setText("Listar Funcionários");
        listarFuncionarios.addActionListener(this::listarFuncionariosActionPerformed);
        menuListar.add(listarFuncionarios);

        listarDependentes.setText("Listar Dependentes");
        listarDependentes.addActionListener(this::listarDependentesActionPerformed);
        menuListar.add(listarDependentes);

        jMenuBar1.add(menuListar);

        menuDeletar.setText("Deletar");

        deletarFuncionario.setText("Deletar Funcionário");
        deletarFuncionario.addActionListener(this::deletarFuncionarioActionPerformed);
        menuDeletar.add(deletarFuncionario);

        deletarDependente.setText("Deletar Dependente");
        deletarDependente.addActionListener(this::deletarDependenteActionPerformed);
        menuDeletar.add(deletarDependente);

        jMenuBar1.add(menuDeletar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarDependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarDependenteActionPerformed
        // TODO add your handling code here:
        dependentes.cadastrarDependente(f);
    }//GEN-LAST:event_cadastrarDependenteActionPerformed

    private void deletarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarFuncionarioActionPerformed
        // TODO add your handling code here:
        int opcao = JOptionPane.showConfirmDialog(null,"Deseja excluir o funcionário?");
        
        String cpf = JOptionPane.showInputDialog("Digite o CPF do funcionário que deseja apagar:\n");

        if(opcao == JOptionPane.YES_OPTION){
            f.excluir(cpf);
        }
    }//GEN-LAST:event_deletarFuncionarioActionPerformed

    private void deletarDependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletarDependenteActionPerformed
        // TODO add your handling code here:
        String cpfDependente = JOptionPane.showInputDialog("Digite o CPF do dependente que deseja apagar:\n");
        
        dependentes.excluirDependente(cpfDependente);
        
    }//GEN-LAST:event_deletarDependenteActionPerformed

    private void cadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncionarioActionPerformed
        // TODO add your handling code here:

        f.nome = JOptionPane.showInputDialog("Nome:");
        f.cpf = JOptionPane.showInputDialog("CPF:");
        f.cargo = JOptionPane.showInputDialog("Cargo:");
        f.salario = Double.parseDouble(JOptionPane.showInputDialog("Salário:"));

        f.cadastrar();
    }//GEN-LAST:event_cadastrarFuncionarioActionPerformed

    private void editarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFuncionarioActionPerformed
        // TODO add your handling code here:

        String novoNome = JOptionPane.showInputDialog("Novo nome:");
        String novoCargo = JOptionPane.showInputDialog("Novo cargo:");
        double novoSalario = Double.parseDouble(JOptionPane.showInputDialog("Novo salário:"));
        String novoCpf = JOptionPane.showInputDialog("Digite o CPF do usuário que terá os dados alterados:");

        f.editar(novoNome,novoCargo,novoSalario, novoCpf);
    }//GEN-LAST:event_editarFuncionarioActionPerformed

    private void editarDependenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarDependenteActionPerformed
        
        String novoNome = JOptionPane.showInputDialog(null,"Digite o novo nome: ","Editar Credenciais do Dependente",1);
        String novoCpf = JOptionPane.showInputDialog("Digite o CPF do usuário que terá os dados alterados:");
        dependentes.editarDependente(novoNome, novoCpf);
    }//GEN-LAST:event_editarDependenteActionPerformed

    private void listarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarFuncionariosActionPerformed
        if(f.exibir().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não há registro de funcionários.", "AVISO", 2);
            return;
        }
        
        String listaBanco = f.exibir();
        
        txtAreaListagem.setText(listaBanco);
        
        jScrollPane1.setVisible(true);
        this.revalidate();
        this.repaint();
        this.pack();
    }//GEN-LAST:event_listarFuncionariosActionPerformed

    private void listarDependentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarDependentesActionPerformed
        // TODO add your handling code here:                                               
        if(dependentes.listarDependentes().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Não há registro de dependentes.", "AVISO", 2);
            return;
        }
        
        String listaBanco = dependentes.listarDependentes();
        
        txtAreaListagem.setText(listaBanco);
        
        jScrollPane1.setVisible(true);
        this.revalidate();
        this.repaint();
        this.pack();
    }//GEN-LAST:event_listarDependentesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem cadastrarDependente;
    private javax.swing.JMenuItem cadastrarFuncionario;
    private javax.swing.JMenuItem deletarDependente;
    private javax.swing.JMenuItem deletarFuncionario;
    private javax.swing.JMenuItem editarDependente;
    private javax.swing.JMenuItem editarFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem listarDependentes;
    private javax.swing.JMenuItem listarFuncionarios;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenu menuDeletar;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuListar;
    private javax.swing.JTextArea txtAreaListagem;
    // End of variables declaration//GEN-END:variables
}